//HintName: ServiceCollectionExtensions.g.cs
// <auto-generated />
// This file is auto-generated by Shiny.Extensions.Localization.Generator
// Do not edit this file directly, instead edit the .resx files in your project.
using global::Microsoft.Extensions.DependencyInjection;

namespace MyTest;

public static class ServiceCollectionExtensions_Generated
{
	public static void AddStronglyTypedLocalizations(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
	{
		services.AddSingleton<global::MyTest.StringsLocalized>();
	}
}