name: Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

  push:
    branches:
    - master
    - dev
    - preview
    - v*
    paths:
    - "src/**"
    - ".github/workflows/**"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '7.0.x'

    - name: Add .NET Workloads
      run: dotnet workload install maui-ios maui-android maui-maccatalyst ios android maccatalyst

    - name: Build
      run: dotnet build Build.slnf /restore -m -property:Configuration=Release -property:PublicRelease=true

    - name: Post NuGet Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget-artifacts
        path: '**/*.nupkg'

    - name: Publish NuGets
      if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/v') }}
      run: dotnet nuget push **\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETAPIKEY }} --skip-duplicate